### ISSUE TITLE
compiam does not seem to be registered with PyPI

### ISSUE THREAD

**Issue by krsnaa** [MTG/compIAM#74]
`pip install compiam` throws errors 

On Colab, upon performing:
`pip install compiam`, the following error is thrown:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement compiam (from versions: none)
ERROR: No matching distribution found for compiam

Even https://pypi.org/simple/compiam/ returns a 404.

Python version is v3.8.16

**Comment by genisplaja** [comment]
Hello @krsnaa, we are sorry for the misunderstanding. We are in process of uploading the first version of compiam to pypi, it should be there by tomorrow. If you are willing to use compiam now, you can install from source (steps specified in README) or try running: pip install `git+https://github.com/MTG/compIAM.git`. Sorry again for the misleading message in the README.md and we will let you know as soon as compiam is ready in pypi. Thanks!!

**Comment by krsnaa** [comment]
Hi @genisplaja, Thanks so much for the follow-up. I was able to install it comfortably from the source and got it to work successfully.

**Comment by genisplaja** [comment]
cool! Just letting you know that `compiam` is now available in PyPI (v0.2.1), so `pip install compiam` will properly install this version.
