### ISSUE TITLE
Issue with scikit-learn version

### ISSUE THREAD

**Issue by snnithya** [MTG/compIAM#89]
On Google Colab, I am unable to successfully install compiam with pip. This appears to be due to a version issue with scikit-learn I think. I have attached the output below.

Python version: 3.10.12

`!pip install compiam`
Collecting compiam
  Using cached compiam-0.2.1.tar.gz (67.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from compiam) (3.7.1)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.10/dist-packages (from compiam) (1.23.5)
Requirement already satisfied: librosa==0.8.0 in /usr/local/lib/python3.10/dist-packages (from compiam) (0.8.0)
Requirement already satisfied: SoundFile==0.10.3.post1 in /usr/local/lib/python3.10/dist-packages (from compiam) (0.10.3.post1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from compiam) (1.3.2)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from compiam) (4.6.0.66)
Requirement already satisfied: pathlib~=1.0.1 in /usr/local/lib/python3.10/dist-packages (from compiam) (1.0.1)
Requirement already satisfied: pytsmod==0.3.3 in /usr/local/lib/python3.10/dist-packages (from compiam) (0.3.3)
Collecting scikit-learn~=0.24.2 (from compiam)
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

=======================================

### Potential solution
1. I cloned the repository with `!git clone https://github.com/MTG/compIAM.git` 
2. Changed the version of scikit-learn to `1.2.2` from `0.24.2` in the `requirements.txt` file. 
3. After this I explicitly downloaded the requirements with `!pip install -r /content/compIAM/requirements.txt` which appeared to work successfully. So I think it might just be a version issue.

**Comment by genisplaja** [comment]
Hello @snnithya. Thanks for bringing this issue up! We are working on compIAM maintenance right now, so thanks for pointing out the issue and solution. We are gonna be adding multiple fixes in the following weeks and release a new compIAM version soon. Cheers!
